name: ci_test

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 官方 Linux 托管 Runner（默认推荐）
    steps:
      - uses: actions/checkout@v4
      - name: 执行命令
        run: echo "使用默认的 GitHub 托管 Runner 运行！"